// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB7bpQ861TsPkCqeF_D5822xjYqmlRXpH4',
    appId: '1:583160827071:web:65389d087800b36f214a0a',
    messagingSenderId: '583160827071',
    projectId: 'emergencyresponse-8e3cd',
    authDomain: 'emergencyresponse-8e3cd.firebaseapp.com',
    storageBucket: 'emergencyresponse-8e3cd.firebasestorage.app',
    measurementId: 'G-RZ5JDGE9Y0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDkoYExn8j5fDkOwWhxlHxR4leIsLAhtew',
    appId: '1:583160827071:android:f07eb7f4420b0e49214a0a',
    messagingSenderId: '583160827071',
    projectId: 'emergencyresponse-8e3cd',
    storageBucket: 'emergencyresponse-8e3cd.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB6BSPQin33nIfxmC0szoZh4QEW55oWVsk',
    appId: '1:583160827071:ios:a7b600377c3ad6dd214a0a',
    messagingSenderId: '583160827071',
    projectId: 'emergencyresponse-8e3cd',
    storageBucket: 'emergencyresponse-8e3cd.firebasestorage.app',
    androidClientId:
        '583160827071-k1he2os9ktag8n4ff9k5icdh96hm5hp9.apps.googleusercontent.com',
    iosClientId:
        '583160827071-rpmbrvt3idha78k87etc40eal8i7gmq1.apps.googleusercontent.com',
    iosBundleId: 'com.journeyai.system.journeyai',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB6BSPQin33nIfxmC0szoZh4QEW55oWVsk',
    appId: '1:583160827071:ios:a7b600377c3ad6dd214a0a',
    messagingSenderId: '583160827071',
    projectId: 'emergencyresponse-8e3cd',
    storageBucket: 'emergencyresponse-8e3cd.firebasestorage.app',
    androidClientId:
        '583160827071-k1he2os9ktag8n4ff9k5icdh96hm5hp9.apps.googleusercontent.com',
    iosClientId:
        '583160827071-rpmbrvt3idha78k87etc40eal8i7gmq1.apps.googleusercontent.com',
    iosBundleId: 'com.journeyai.system.journeyai',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB7bpQ861TsPkCqeF_D5822xjYqmlRXpH4',
    appId: '1:583160827071:web:20d5ca7813889337214a0a',
    messagingSenderId: '583160827071',
    projectId: 'emergencyresponse-8e3cd',
    authDomain: 'emergencyresponse-8e3cd.firebaseapp.com',
    storageBucket: 'emergencyresponse-8e3cd.firebasestorage.app',
    measurementId: 'G-SKYYQBP0VE',
  );
}
