# Uncomment the next line to define a global platform for your project
platform :ios, '13.0'

target 'Runner' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  source 'https://cdn.cocoapods.org/'
  # Pods for Runner
  pod 'StripePaymentSheet'

  target 'RunnerTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
